CREATE DATABASE IF NOT EXISTS social_news;

USE social_news;

CREATE TABLE IF NOT EXISTS users (
  idUsers INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(20) DEFAULT NULL,
  password VARCHAR(40) DEFAULT NULL,
  name VARCHAR(45) DEFAULT NULL,
  lastName VARCHAR(45) DEFAULT NULL,
  birth DATE DEFAULT NULL,
  email VARCHAR(45) DEFAULT NULL,
  permitionLevel INT(11) DEFAULT NULL,
  PRIMARY KEY (idUsers)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS news (
  idNews INT(11) NOT NULL AUTO_INCREMENT,
  Users_idUsers INT(11) NOT NULL,
  title VARCHAR(60) DEFAULT NULL,
  text TEXT DEFAULT NULL,
  tags TINYTEXT DEFAULT NULL,
  date DATETIME DEFAULT NULL,
  url TINYTEXT DEFAULT NULL,
  PRIMARY KEY (idNews)
) ENGINE=InnoDB;

ALTER TABLE news
ADD CONSTRAINT FK_news
FOREIGN KEY (Users_idUsers) REFERENCES users(idUsers)
ON UPDATE CASCADE
ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS comments (
  idComments INT(11) NOT NULL AUTO_INCREMENT,
  Users_idUsers INT(11) NOT NULL,
  News_idNews INT(11) NOT NULL,
  comment TEXT DEFAULT NULL,
  PRIMARY KEY (idComments)
) ENGINE=InnoDB;

ALTER TABLE comments
ADD CONSTRAINT FK_comments
FOREIGN KEY (Users_idUsers) REFERENCES users(idUsers)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE comments
ADD CONSTRAINT FK_comments1
FOREIGN KEY (News_idNews) REFERENCES news(idNews)
ON UPDATE CASCADE
ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS favorites (
  idFavorites INT(11) NOT NULL AUTO_INCREMENT,
  Users_idUsers INT(11) NOT NULL,
  urlNew TINYTEXT DEFAULT NULL,
  titleNew VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (idFavorites)
) ENGINE=InnoDB;

ALTER TABLE favorites
ADD CONSTRAINT FK_favorites
FOREIGN KEY (Users_idUsers) REFERENCES users(idUsers)
ON UPDATE CASCADE
ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS servers (
  idServers INT(11) NOT NULL AUTO_INCREMENT,
  urlServer TINYTEXT DEFAULT NULL,
  nameServer VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (idServers)
) ENGINE=InnoDB;
